export const products = [
    {
        id: 1,
        name: 'iPhone 14',
        description: 'Najnowsza wersja iPhone z wieloma nowymi funkcjami!',
        price: 4999,
        currency: 'PLN',
        promo: false,
    },
    {
        id: 2,
        name: 'Samsung Galaxy S22',
        description: 'Potężny smartfon z Androidem i niesamowitym wyświetlaczem.',
        price: 4499,
        currency: 'PLN',
        promo: false,
    },
    {
        id: 3,
        name: 'MacBook Pro 2023',
        description: 'Najnowszy MacBook Pro z mocnym procesorem i Retiną XDR.',
        price: 8999,
        currency: 'PLN',
        promo: false,
    },
    {
        id: 4,
        name: 'Sony PlayStation 5',
        description: 'Konsola do gier z obsługą 4K i superszybkim SSD.',
        price: 2299,
        currency: 'PLN',
        promo: false,
    },
    {
        id: 5,
        name: 'Nikon D850',
        description: 'Profesjonalna lustrzanka cyfrowa z dużym sensorem i 4K.',
        price: 7499,
        currency: 'PLN',
        promo: false,
    },
    {
        id: 6,
        name: 'Apple Watch Series 7',
        description: 'Najnowszy smartwatch od Apple z większym ekranem i nowymi funkcjami.',
        price: 1499,
        currency: 'PLN',
        promo: false,
    },
    {
        id: 7,
        name: 'Dell XPS 13',
        description: 'Ultraportatwny laptop z ekranem InfinityEdge i mocnymi podzespołami.',
        price: 5699,
        currency: 'PLN',
        promo: true,
    },
    {
        id: 8,
        name: 'Bose QuietComfort 45',
        description: 'Najnowsze słuchawki douszne z doskonałym tłumieniem hałasu.',
        price: 899,
        currency: 'PLN',
        promo: false,
    }
];